[tool.black]
line-length = 120
skip-string-normalization = true

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120

known_django = "django"
known_pandas = "pandas,numpy"
sections = "FUTURE,STDLIB,THIRDPARTY,DJANGO,PANDAS,FIRSTPARTY,LOCALFOLDER"

import_heading_stdlib = "Standart library imports"
import_heading_thirdparty = "Thirdparty imports"
import_heading_firstparty = "Local imports"
import_heading_localfolder = "Local folder imports"
